Create en_US translation properties
Frooodle/Stirling-PDF pull request #301
Opened 2023-08-10 15:56 UTC by jb2barrels

Copied from en_GB. Fixed variables noFavourites and home.pdfOrganiser.title to use its US corrected spelling.

2023-08-10 19:10 UTC, Frooodle commented
Can you also add flag svg and navbar.html change?

2023-08-10 19:15 UTC, Frooodle requested changes

2023-08-10 19:15 UTC, Frooodle commented on src/main/resources/messages_en_US.properties
> +pdfOrganiser.title=Page Organiser
z need here

2023-08-10 19:15 UTC, Frooodle commented on src/main/resources/messages_en_US.properties
> +pdfToImage.colorType=Colour type
color

2023-08-10 19:15 UTC, Frooodle commented on src/main/resources/messages_en_US.properties
> +pdfToImage.grey=Greyscale
gray

2023-08-10 20:34 UTC, jb2barrels commented
@Frooodle Thank you for the additional US language correction point outs.
As requested I've also added the US svg and navbar changes.

2023-08-10 20:41 UTC, Frooodle approved these changes

2023-08-10 20:42 UTC, merged

2023-10-08 19:09 UTC, Frooodle commented
Hi jb2barrels,

We are updating Stirling-PDF's license to MPL 2.0 (Mozilla Public License Version 2.0) to continue fostering our open-source commitment while introducing more flexible usage of the project.

### What We Need From You:
In order to transition to the MPL 2.0 license, we need the explicit consent of all our contributors. 
1. If you're comfortable relicensing your contributions for this specific PR under MPL 2.0, please respond with:
`
I, jb2barrels, grant permission to relicense my contributions from this PR to Stirling-PDF under the Mozilla Public License 2.0. 
`
2. If you'd prefer to give blanket permission for all of your contributions to Stirling-PDF (be it through pull requests, commits, or any other form of contribution) rather than on a PR-by-PR basis, please respond with:
`
I, jb2barrels, grant permission to relicense all my contributions to Stirling-PDF under the Mozilla Public License 2.0.
`

### What does this do and why?
As your old code was contributed under a different license it legally cannot move to a new license without your permission, and since we dont want to lose your code we wanted to reach out. Remember this project is remaining open-source!.

### Deadline:
If we dont receive a response, or if you decline, unfortunately, we will have to remove your contributions from Stirling-PDF before the license change, which is scheduled  in coming months.

### Thank You! 
Your contributions are invaluable, and we hope to continue having them in Stirling-PDF under the new license. Feel free to ask if you have any questions or concerns about this change.

Best,
Frooodle
Stirling-PDF Maintainer

2023-10-10 21:55 UTC, jb2barrels commented
I, jb2barrels, grant permission to relicense my contributions from this PR to Stirling-PDF under the Mozilla Public License 2.